FROM python:3.10-slim

# Install dependencies
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install fastapi uvicorn sqlalchemy pytz sqlmodel sqlalchemy-utils psycopg2-binary minio python-multipart Pillow

CMD ["python", "api.py"]